### ISSUE TITLE
Exception thrown during startup

### ISSUE THREAD

**Issue by qq253498229** [oskros/MF_counter_releases#15]
23:09:57,2 root ERROR 'utf-8' codec can't decode byte 0xc2 in position 2: invalid continuation byte
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "master_frame.py", line 156, in __init__
  File "modules\mf_timer.py", line 35, in __init__
  File "modules\mf_timer.py", line 78, in _update_timers
  File "modules\mf_timer.py", line 93, in _update_session_time
  File "modules\mf_timer.py", line 90, in is_game_open
  File "memory_reader\reader_utils.py", line 158, in one_of_processes_exists
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 2: invalid continuation byte

**Comment by oskros** [comment]
Do you have chinese characters in the path where you placed the MF run counter exe?

**Comment by qq253498229** [comment]
It seems not. My app path is: D:\game\mfruncounter

**Comment by qq253498229** [comment]
[mfruncounter.zip](https://github.com/oskros/MF_run_counter/files/10046436/mfruncounter.zip)
Here is the generate files, exclude the exe file I download on release page.

**Comment by oskros** [comment]
Ahh its actually the install path of diablo that might have chinese characters in it

**Comment by qq253498229** [comment]
D:\game\Diablo II Resurrected

**Comment by qq253498229** [comment]
There is also no Chinese.

**Comment by qq253498229** [comment]
There is also no Chinese.

**Comment by qq253498229** [comment]
Because I am also a programmer, I usually do not use the Chinese path for filename or path.

**Comment by oskros** [comment]
Hmm strange. Its just that the error is related to a decoding problem, which i assumed came from a chinese character. But I can maybe try another encoding

**Comment by qq253498229** [comment]
19:12:22,83 root ERROR (<class 'UnicodeDecodeError'>, UnicodeDecodeError('utf-8', b'\xb0\xd9\xb6\xc8\xb7\xad\xd2\xeb.exe', 0, 1, 'invalid start byte'), <traceback object at 0x000002835A130080>)
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "tkinter\__init__.py", line 804, in callit
  File "modules\mf_timer.py", line 78, in _update_timers
  File "modules\mf_timer.py", line 93, in _update_session_time
  File "modules\mf_timer.py", line 90, in is_game_open
  File "memory_reader\reader_utils.py", line 158, in one_of_processes_exists
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

**Comment by qq253498229** [comment]
I found that after I opened an application named "BaiduTranslate" , the MF Run Counter would crash.

**Comment by qq253498229** [comment]
I found that after I opened an application named "BaiduTranslate" , the MF Run Counter would crash.

**Comment by oskros** [comment]
I think I might have found a solution. Can you try this updated version? 
[mf_timer.zip](https://github.com/oskros/MF_run_counter/files/10046931/mf_timer.zip)

**Comment by qq253498229** [comment]
Exciting! Now it can run normally!
